name: Find Deprecated API Files
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to scan in target repository'
        default: 'main'
        required: true

jobs:
  scan-deprecated:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: owner/target-repo-name  # Replace with actual owner/repo
          ref: ${{ inputs.target_branch }}
          token: ${{ secrets.PAT_TOKEN }}  # Need a PAT if repo is private
          
      - name: Search for deprecated APIs
        id: search
        run: |
          # Create results directory
          mkdir -p results
          
          # Perform search and save results
          echo "### Deprecated API Files Found ($(date '+%Y-%m-%d'))" > results/report.md
          echo "Branch: ${{ inputs.target_branch }}" >> results/report.md
          echo "" >> results/report.md
          echo "Files containing '(deprecated)' in title:" >> results/report.md
          echo "\`\`\`" >> results/report.md
          
          # Main search command with error handling
          if ! find api-reference/beta/api -name "*.md" -type f -exec grep -l "title:.*\(deprecated\)" {} \; > results/files.txt; then
            echo "::error::Search command failed"
            exit 1
          fi
          
          # Count files and store as output
          COUNT=$(wc -l < results/files.txt)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          
          # Add results to report
          cat results/files.txt >> results/report.md
          echo "\`\`\`" >> results/report.md
          
          # Add summary
          echo "" >> results/report.md
          echo "Total files found: $COUNT" >> results/report.md

      - name: Upload results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deprecated-api-scan
          path: results/
          retention-days: 90
